[package]
name = "pine"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
image = "0.25.9"
ratatui = "0.29.0"
ratatui-image = "8.1.1"
tui-textarea = "0.7.0"
